<?php

namespace AppBundle\Repository;

/**
 * LoanedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanedRepository extends \Doctrine\ORM\EntityRepository
{
}
